# Generated by Django 5.0.2 on 2024-02-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_student_roll_no_alter_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.IntegerField(max_length=100),
        ),
    ]
